language: java
sudo: required
addons:
  ulimit:
    nofile: 1048576
services:
- docker
jdk:
- oraclejdk8
script: "./gradlew clean test dist"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FcTs4ABn8tjRqWZPCELDJzs0BqG7CGzkHWtxsXVpN43ABUhCt+BJivd1Vm8F/TWixG8KQ5/qtqhPvsdn06ObxAryshmKVbaOglAchOlXmjscuPYfDnZ28AlR84yQSYusSPXvN7zTmIkH/c76AvOoe1K9imiwZP59CJocGC5YRA/hOK0yDDzxyMrB44uYu5KVDT/RDqasL5Gf2pHMUU2xWsEqUN77EXpKZ0UAm+JaX1N3ZPnOUQO947MU/PHmS1Pfzq+hgzHhTa8xNfDbuWlZH3PXhESoiGzRiEJyD3Ks6nKwgL7r+ti8GB5ZSTC9p0YD8t1N5uxfROG3suiVdoRy/Ecn2bKcVWCVmIv+v9bolUXlB7f99tyhoXYxT3uqbnML3jK9cBdf/Hgjw02wS4N4aSQF10XYbyHNdsyE4xt37kZkKnCj57YT6bYl2AwRAfJA92oWGpobQjFOvTXWbzFPXQTMOW5V/IICyU4U6SFd8bbXRMZIr8t5tX5jj73oQrw0+4pvwRVnebkHL6HMJroI1jsOWg0s8i3h2m62dkbP3H1Hq12LgXIlIzoQm0zQr/ontY925zgmcQhqwj5I/Ze3CGfXulHJr0/DMGyrsetifMpQOGbRH9uNMdmwAXiYeLeokxW9dIKYbkLrrdMTDkb8WAWzn0VUHgiWluRS6B11heI=
  file_glob: true
  file:
  - "./build/dist/nagaina-*.tgz"
  on:
    tags: true
env:
  global:
    matrix:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: Awm5ZsL8OJZTu6laZWGgm0kixqCQaAWnR7du+tMphQEra62axza+M5Dtj6OqmLXygtjirKUawEODN9oW64YAUqvWBy3ZV6b+x43Ixbh3dTTTGCkk9o0AbguGN3mcVyASf/FhXHsCR209dEmBN7rOxv1H/FXOsTBL7FrkrjB25SwRouiJa5q3ji2HsZXEIV8kpZ+l8eb8X4zuMpWfUJtqtzZ5Ozbr2UrL3EadImhfFzDqNggDZBZIYL5bsZk/7dJ2ATpHznqaWfRWw7KxKjZ/QCdjoquVQEnWt6Mg2dUh3eDzoynnDor7TTUrekSsJLFecfyRL6+1Y3KrgPxj1eiRqllCKbVNLzQltU5lrM5vMA3SzAJ/5HoRbqRiksKJrw+e/sE0WKeh48O+qMkdmOpLtdrdZMq9cguSmFUFTwOfh3X02z7KcdGixYNcu2jrwuPxt02hc0NxF2viv5vriagtFredTcGIT8hDUNh4ARCFsm2JH5TXkgdovTUYNfd1EFMVKsPp7WC73cRv+Hreex1MmkEbQkP9iHRwxVf7du3gWhJOvtiaXrZIk1Hi9lEiMjuqTrBFh5wpsOWM6Zhj1JCrdgH9OqmeatOrstZbjJu3U/ZEIsCsxFvI37+wpa2cgtGVUVgMxFQm2XEPzUM3QdU/1rsDVXIW6oylTlCM85qPy2Q=
    - secure: rqGxUKnBladWD+2SuRBit/eLnJD/nZNoT0Gl1HW0GiQaI+OL38PDtIrEiQJBI8yBjj70SGGIMCaGhXifpQLUIBcnBLjtFj4ztvhIG9ooDQZcf6jVu0BgpfNzXgHKKJN4uM1bQb2upljmVaIrSDfrYitVHtPoxgp0JWESym/a2ITwhZ863OgmqKsVJm3uFhHJC1qle6OUTcgT0fI+o/XVATuqu6WbxH6YdUgIEwCjiaA8xcCY0TXt89R2cu7Tq9GbdNQVzTxwWpBRP7/JC9pzwQTsCNsAA++rkvMkNb2StPK5xDmqDNf91hfjv0ZNIxhIRRBKRr8V7p9sb4dPOxjdZkcKFzGWaNxFMqa3cMts1BYki/ZeRDEJmmRk/Z2ocKfHh0C0MLfL9JGkeG355oEFclKDZbpLzMUlg/B+oxzht6NnXCmOw0LzJxcxq9m9zEbWCaXmPCRvdkGOG0Bj+MvEFgxfyXRPhOSJayggIXx02YZN1HfUiKUZg8p1M54HyOEpaQEzSfjMRaGXhCOW6kHbYpJFeJYI+4weEDaivTfts1RvnB/84ZGl4hY5faTUnV56KzKOreh8V6UfQiriMr5h5qdBnK1J7Olz0Bc+T2q33zL5rqgeMiEMq2+YDqsBfC/UwE/lO5S6PHyONKm16+lqrZY3ay/cvXrhb/Rll2gPxgk=
    - secure: JT3awhA8DPSKDmBv0ByCX1ri23rPDl5gKQr0XlR683L3pxjafyto3hHop0UDkztweQuFrXka+NnI3VJhEnfmccoK91v7C17SlfamqHGvp562AIXOBrSVKUgDdq8nDtPMvIcVj1SW/hyKlkLrTmPJYBjwpGN6moS67kN09S6p9RIDG3FqNSzmHmzqyGfFM41mY3gAXQLibjE5RLYiA+E4MMxww+O2ngln1eVRs0p025xPqFlW4n3z3DevhEmAv4jJ72lyNnDfb4SCm1Y41EIMrGE9wdspcSI3VNuB3lFpKobr5ynPH6kYZLgefJS5wcvqu1SgM6i45OyXCIOvpq94nf/PssvrSwk3aGNGTZLhdQ8brhSzbLS1tKJ2Ts4nCUAiq+OQx/jyOG7+xJTSQpZWG9QH8dHsNZnHmGFo48nrZifvMzjAln1jAhPdu97A2aV2atvUoPR+8HogvrDpdRjKRCkjicimQk0a2y4Ij30KwUfPD4ubpRTteTYUW2C4RVznCWzZrhPFQ2XYDxpPHgwG71UUwzGvEW83DEFSKOI7ohaBj2pksnJ429QHlGlb8HiQrbEP3tfutIVXY6teGYpZnZ2dDlgREzxdDHuzU8m/w19YUQUiyUrHdLEc5vSUOBclG59afeIHSgdXKtHLffv+7dvT1SZlYcmukTMeuvwLnKk=
    DOCKER_USER:
      secure: Wi52uI5thNagDmiKWzu4/ZI52MIYMOueWp4G1rM9FPEFs4Fs8NFtHIfavs+OV9eDupFgO0+cY16pdGIGisK0/Xaz3il3UACoCpFg2j6C2Su7KQQhvAYPInGgXfVyX3Si5axv4gM2S5LgYumDnP506yWXfd/XA732xFQKvtQwjjGkVVbQ3NXJBH0fYv6emE0dmN6BQ3Pz/BRqY1koRG8dJvueOcRO4XNShZXdG2glUFMzniES4OuguDyyLvvFqZLWCRV54y91dLBV8hdYTWYAm6l8zaYShR+2s/1wIkpsY1KblZu2vFOuL9aILXBiNM6LKeLh+ryG1Jy90DetMowh/GASXs+TVoywZEQInGOSYQuS79kkWVn1wbwCnhLO2P+LTDyhRfFV8+xCd7XSLI4OZw4cEeRCIszLPOy9Wj+3Y1bXkWTFDdOMTE1/J9OdRZb4+4LWD9orcqiq0JltVCe4O/XuHL/VIdqAzTQkQtXdbNZCbb+S8dRNhLsQlWMS2rhdLEnoCkga7bKTBzevMag6ClNYY6x35ekjo9dmsYx3GEMxfEJec5DTjCyc5MkiCSuBIbExzPb58RDAY2pk2JEBZMP9Xs1tIFNMiT0o6scf40sr/qeFVmlRuwmvh1LWsaK1Tb6QNHE3BNH1y/ACnrg1tXdWLjVvLvt8zAvwR7Azu7E=
    DOCKER_PASS:
      secure: CDTERDY3FuqyGMw7uM/Qm1SwgrhoLd+6dCeELOEPrzodrkcDXWrkoEHB1uLY2xxn/NDI12LAiXEo4qFIisZowRnuWMYh+tKfUnr4dP33aVXNFS8XbQufJHMmJCiTxtMb4Oz2jYB11ufD7ACJmuBpDxM3dIeyaWR1UjI/wDG+EDc6C0vVQ9msiXJx7ExBB+SsUJPoUMAuGVmU3TpaKctIWgAHyTsxXCYK7mIwgQISVnseVgDX+6AAajfiQWkI6ypmkKDcdju//sL6v+C1k2U7GaFCb7gZTN6wWuWPxKOgg7sodgJuIZ//3M6l/mq+iLCRm34NWGSg8w8xjrmVcq70LSx/VdDvtx66qhGKFMh+WRwRsHuP7xJ1dfBk6Mj7g03/0VnXO4Zw3C+2fSbvX7gbbht4QZ7RKReNzAOkd2YKy2+X9Ky7JU4y6/6ZhFeewZjnAKmnlOQ4PkmWntQXB1Z0RGrvYyksKfa3No9XKkpxJDflSb3ZaTyyOvoLXe2aw9LLW4DzvIBHgxEdO/UlejTZAcFDsJgE9wUOQh43vij7/ew+/wwNSZ3dmZ79PUuy1LlPBnoXvXIwT8gWfQVPMPyvgcu4W0CnXwIQsGYnpfsw4iMlgu1VqKNTkO+HEcQHfcPNf9ZvFpSETBiNdHxkYKk4Iu+Sw43G+KCju39P51/IOpY=
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
matrix:
  fast_finish: true
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=emcmongoose/nagaina
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -f docker/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
